/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package invernadero;

import invernadero.models.*;
import invernadero.reports.*;

public class App {

    public static void main(String[] args) {
        try {
            Config config = new Config().load();
            Report report = new Report(config);
            report.generateReports();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
}
